### ISSUE TITLE
域名拼接问题

### ISSUE THREAD

**Issue by Joezhangs** [tiann/super-adb#1]
https://gank.io/2016/10/20后面的/2016/10/20这个正斜杠怎么打上去的啊。每次打正斜杠他都翻译成-。

**Comment by tiann** [comment]
与本hub无关 ^_^ ；不过你可以搜一下url转义

**Comment by Joezhangs** [comment]
![qq 20161025102907](https://cloud.githubusercontent.com/assets/15052128/19671010/567e76a2-9a9e-11e6-9c33-89e3d2d79ba1.png)
那这个日期当中的-如何变成/

**Comment by tiann** [comment]
github的库名字不允许出现  /  ，你输入 /  会自动给你转成  -

**Comment by Joezhangs** [comment]
![xxxx](https://cloud.githubusercontent.com/assets/15052128/19671359/b1d69ee2-9aa0-11e6-9f2b-1ac0bcbf2580.png)
这个为什么可以呢

**Comment by tiann** [comment]
一个是github库的名字，这是github的规定；一个是一个网站的url，完全八竿子打不着啊。

**Comment by Joezhangs** [comment]
但是我觉得github库的名字好像就是定义了网站的连接。
![image](https://cloud.githubusercontent.com/assets/15052128/19671524/e36f2644-9aa1-11e6-9093-249951f7f8d1.png)
我就想可不可以改下这个网站的名字，我-改成/.如若不是这样，请教下这个网站怎么改啊

**Comment by tiann** [comment]
何必在这些问题上纠结呢？

github让你这么用，你就怎么用呗；如果你想自定义，那就自己搭建博客；但是，为什么要浪费时间在这里呢？有这个精力多看几本书不是更好。

**Comment by Joezhangs** [comment]
恩。我可以加下你的QQ吗。以后有问题想咨询您。
