### ISSUE TITLE
syntax error when install busybox

### ISSUE THREAD

**Issue by samsun639** [tiann/super-adb#2]
python version:Python 2.7.6
pexpect in /usr/lib/python2.7/dist-packages
android: 7.1.1

the first time run "super_adb" 

ls: /data/local/tmp/busybox: No such file or directory
install busybox...
download busybox binary...
 2730% completechange permission : 
/data/local/tmp/busybox[1]: syntax error: 'newline' unexpected
install busybox : 
export PATH=/data/local/tmp/:$PATHsdm660_64:/ $ export PATH=/data/local/tmp/:$PATH

then in adb shell:
/data/local/tmp # busybox
/data/local/tmp//busybox[1]: syntax error: 'newline' unexpected

**Comment by samsun639** [comment]
in adb shell:
/data/local/tmp # busybox                                            
/data/local/tmp//busybox[1]: syntax error: 'newline' unexpected

**Comment by tiann** [comment]
@samsun639 The download url supplied by busybox is dead, I have made a backup in this project. It can work properly now.
